# Generated by Django 5.0.7 on 2024-07-19 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('weather_description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогнозы погоды',
                'ordering': ['-date_time'],
            },
        ),
    ]
